### ISSUE TITLE
Incoherent licensing declaration for FioSynth

### ISSUE THREAD

**Issue by Conan-Kudo** [facebookincubator/FioSynth#1]
I was looking at this project and I noticed that the licensing declarations are incoherent.

The [setuptools metadata](https://github.com/facebookincubator/FioSynth/blob/8f338fff283b36c6615096e36c0785cee02a5059/setup.py) indicates it's `BSD+PATENTS` which is generally not considered an OSS license, but further evaluation of the licensing data presents a different picture:

* The [`LICENSE`](https://github.com/facebookincubator/FioSynth/blob/8f338fff283b36c6615096e36c0785cee02a5059/LICENSE) file is the standard 3-clause BSD license, which _is_ an accepted OSS license
* The [`PATENTS`](https://github.com/facebookincubator/FioSynth/blob/8f338fff283b36c6615096e36c0785cee02a5059/PATENTS) file is actually the MIT license instead of some kind of patent license document, which... makes no sense?

`fio` itself is GPLv2, so there were no clues from that for what this project is _supposed_ to be licensed.

If I were to take a stab at this, I'd suggest this was probably intended to be just licensed under the BSD license (no `PATENTS` file). But I might suggest also just licensing it under the same terms that `fio` itself is licensed under (GPLv2).

**Comment by davide125** [comment]
Sorry for the delay, this took a while to sort out. With https://github.com/facebookincubator/FioSynth/commit/67905b1b1ba57d3d552122c13192e50ee5523f3c and https://github.com/facebookincubator/FioSynth/commit/5d9cf010c785b1f847f298ca17b194c12eae3049 FioSynth should be fully relicensed to MIT.

**Comment by Conan-Kudo** [comment]
Yeah, this looks sorted out to my satisfaction. Thanks for this!
